// examples/ssr/workers/react-router/src/index.tsx
import { renderToString } from "react-dom/server";
import { StaticRouter } from "react-router";

import vFrameInlineScript from "../../host/generated/v-frame-inline.txt";
import {
  isWidgetRoute,
  ReleaseActivityWidget,
  type WidgetRoute,
  widgetStyle,
} from "./widget";

const clientModulePath = "/assets/react-router-widget-client.js";
const contentType = "text/html; charset=utf-8";
const embeddedVFrameScript = vFrameInlineScript.replace(/<\/script/gi, "<\\/script");

interface RenderContext {
  basename: string;
  route: WidgetRoute;
  routingFrameId: string;
  virtualPath: string;
}

function normalizedBasePath(value: string | null): string {
  if (value === null || !value.startsWith("/")) {
    return "/";
  }
  const normalized = value.replace(/\/+$/, "");
  return normalized === "" ? "/" : normalized;
}

function requestedRoute(value: string | null): WidgetRoute {
  return value !== null && isWidgetRoute(value) ? value : "/activity";
}

function requestedFrameId(value: string | null): string {
  return value === null ? "react-router-widget" : value;
}

function virtualPath(basename: string, route: WidgetRoute): string {
  return basename === "/" ? route : `${basename}${route}`;
}

function renderContext(basename: string, route: WidgetRoute, routingFrameId: string): RenderContext {
  return { basename, route, routingFrameId, virtualPath: virtualPath(basename, route) };
}

function renderWidget(context: RenderContext): string {
  return renderToString(
    <div
      id="react-router-widget-root"
      data-router-basename={context.basename}
      data-routing-frame-id={context.routingFrameId}
    >
      <StaticRouter basename={context.basename} location={context.virtualPath}>
        <ReleaseActivityWidget routingFrameId={context.routingFrameId} />
      </StaticRouter>
    </div>,
  );
}

function clientModuleURL(basename: string): string {
  return basename === "/" ? clientModulePath : `${basename}${clientModulePath}`;
}

function materializedDocument(markup: string, moduleURL: string): string {
  return `<v-html lang="en"><v-head><style>v-html, v-body { display: block; } v-head { display: none; } ${widgetStyle}</style></v-head><v-body>${markup}<script type="application/vnd.v-frame" data-v-frame-script data-v-frame-type="module" src="${moduleURL}"></script></v-body></v-html>`;
}

function networkDocument(markup: string, moduleURL: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${widgetStyle}</style></head><body>${markup}<script>${embeddedVFrameScript}</script><script type="module" src="${moduleURL}"></script></body></html>`;
}

function documentResponse(context: RenderContext): Response {
  return new Response(networkDocument(renderWidget(context), clientModuleURL(context.basename)), {
    headers: { "Content-Type": contentType },
  });
}

function previewResponse(context: RenderContext): Response {
  return new Response(materializedDocument(renderWidget(context), clientModuleURL(context.basename)), {
    headers: { "Content-Type": contentType },
  });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method !== "GET") {
      return new Response("method not allowed", { status: 405, headers: { Allow: "GET" } });
    }

    const url = new URL(request.url);
    if (url.pathname.startsWith("/widgets/qwik/")) {
      const mountedPath = url.pathname.slice("/widgets/qwik".length);
      let componentPath = mountedPath + url.search;
      if (mountedPath === "/inventory" || mountedPath === "/catalog") {
        const componentParameters = new URLSearchParams({
          route: mountedPath,
          base: "/widgets/qwik/build/",
        });
        if (url.searchParams.get("surface") === "definition") {
          componentParameters.set("surface", "definition");
          const article = url.searchParams.get("article");
          if (article !== null) componentParameters.set("article", article);
        }
        componentPath = `/document?${componentParameters}`;
      }
      return env.QWIK_WIDGET.fetch(new Request(`https://qwik-widget.internal${componentPath}`, {
        headers: { Accept: "text/html" },
      }));
    }
    let context: RenderContext;
    let endpoint: "/document" | "/preview";
    if (isWidgetRoute(url.pathname)) {
      context = renderContext("/", url.pathname, "react-router-widget");
      endpoint = "/document";
    } else if (url.pathname === "/document" || url.pathname === "/preview") {
      context = renderContext(
        normalizedBasePath(url.searchParams.get("base")),
        requestedRoute(url.searchParams.get("route")),
        requestedFrameId(url.searchParams.get("frameId")),
      );
      endpoint = url.pathname;
    } else {
      return new Response("React Router widget not found", { status: 404 });
    }

    const response = endpoint === "/document"
      ? documentResponse(context)
      : previewResponse(context);
    if (context.route === "/plugins") {
      return response;
    }

    const articleKey = context.route === "/research"
      ? "research"
      : context.route === "/brief"
        ? "brief"
        : "migration";

    const nestedPreviewResponse = await env.QWIK_WIDGET.fetch(new Request(
      `https://qwik-widget.internal/preview?route=%2Finventory&base=%2Fwidgets%2Fqwik%2Fbuild%2F&surface=definition&article=${articleKey}`,
      { headers: { Accept: "text/html" } },
    ));
    if (!nestedPreviewResponse.ok) {
      console.error(JSON.stringify({
        message: "Nested SSR widget composition failed",
        status: nestedPreviewResponse.status,
        widget: "qwik",
      }));
      return new Response(
        `Nested SSR widget qwik returned status ${nestedPreviewResponse.status}`,
        { status: 502 },
      );
    }

    const nestedPreview = await nestedPreviewResponse.text();
    return new HTMLRewriter()
      .on("v-frame.nested-workspace-widget", {
        element(element) {
          element.setAttribute("adopt", "");
          element.setInnerContent(
            `<template shadowrootmode="open" shadowrootserializable>${nestedPreview}</template>`,
            { html: true },
          );
        },
      })
      .transform(response);
  },
} satisfies ExportedHandler<Env>;

// examples/ssr/workers/qwik/src/index.tsx
/** @jsxImportSource @builder.io/qwik */
import { renderToStream } from "@builder.io/qwik/server";
import { manifest } from "@qwik-client-manifest";
import {
  isWidgetRoute,
  type RoutingFrameId,
  type WikipediaArticleKey,
  type WidgetRoute,
  widgetStyle,
  WorkspaceWidget,
} from "./widget";

type WidgetEndpoint = WidgetRoute | "/preview" | "/document";

function isWidgetEndpoint(pathname: string): pathname is WidgetEndpoint {
  return isWidgetRoute(pathname) || pathname === "/preview" || pathname === "/document";
}

function widgetBuildBase(url: URL, pathname: WidgetEndpoint): string {
  const requestedBase = url.searchParams.get("base");
  if (requestedBase === "/build/" || requestedBase === "/widgets/qwik/build/") {
    return requestedBase;
  }
  return pathname === "/preview" ? "/widgets/qwik/build/" : "/build/";
}

function requestedRoute(url: URL, pathname: WidgetEndpoint): WidgetRoute {
  if (isWidgetRoute(pathname)) {
    return pathname;
  }
  const route = url.searchParams.get("route");
  return route !== null && isWidgetRoute(route) ? route : "/inventory";
}

function requestedFrameId(url: URL): RoutingFrameId {
  return url.searchParams.get("frameId") === "qwik" ? "qwik" : "";
}

function requestedSurface(url: URL): "definition" | "page" | "profile" {
  const surface = url.searchParams.get("surface");
  if (surface === "definition" || surface === "profile") return surface;
  return "page";
}

function requestedArticle(url: URL): WikipediaArticleKey {
  const article = url.searchParams.get("article");
  if (article === "brief" || article === "research") return article;
  return "migration";
}

async function renderWidget(url: URL, pathname: WidgetEndpoint): Promise<string> {
  const chunks: string[] = [];
  await renderToStream(
    <WorkspaceWidget
      articleKey={requestedArticle(url)}
      initialRoute={requestedRoute(url, pathname)}
      routingFrameId={requestedFrameId(url)}
      surface={requestedSurface(url)}
    />,
    {
      base: widgetBuildBase(url, pathname),
      containerTagName: "div",
      manifest,
      preloader: false,
      qwikLoader: "module",
      snapshot: true,
      stream: {
        write(chunk) {
          chunks.push(chunk);
        },
      },
      streaming: { inOrder: { strategy: "disabled" } },
    },
  );
  return chunks.join("");
}

function inertScripts(markup: string): string {
  return markup.replace(/<script\b([^>]*)>/gi, (_match, attributes: string) => {
    const typeMatch = /\stype=("[^"]*"|'[^']*'|[^\s>]+)/i.exec(attributes);
    const type = typeMatch?.[1].replace(/^['"]|['"]$/g, "");
    const remainingAttributes = attributes
      .replace(/\sdata-v-frame-(?:script|type)(?:=("[^"]*"|'[^']*'|[^\s>]+))?/gi, "")
      .replace(/\stype=("[^"]*"|'[^']*'|[^\s>]+)/gi, "");
    const authoredType = type === undefined ? "" : ` data-v-frame-type="${type}"`;
    return `<script type="application/vnd.v-frame" data-v-frame-script${authoredType}${remainingAttributes}>`;
  });
}

function materializedDocument(markup: string): string {
  return `<v-html lang="en"><v-head><style>v-html, v-body { display: block; } v-head { display: none; } ${widgetStyle}</style></v-head><v-body>${inertScripts(markup)}</v-body></v-html>`;
}

function networkDocument(markup: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${widgetStyle}</style></head><body>${markup}</body></html>`;
}

export default {
  async fetch(request: Request): Promise<Response> {
    if (request.method !== "GET") {
      return new Response("method not allowed", { status: 405, headers: { Allow: "GET" } });
    }

    const url = new URL(request.url);
    const { pathname } = url;
    if (!isWidgetEndpoint(pathname)) {
      return new Response("Qwik widget not found", { status: 404 });
    }

    const markup = await renderWidget(url, pathname);
    return new Response(
      pathname === "/preview" ? materializedDocument(markup) : networkDocument(markup),
      {
        headers: {
          "Cache-Control": "no-store",
          "Content-Type": "text/html; charset=utf-8",
        },
      },
    );
  },
} satisfies ExportedHandler;
