// examples/workers-composition/workers/react-router/src/widget.tsx
import { useState } from "react";
import { Link, Navigate, Route, Routes, useLocation } from "react-router";

import { useWidgetRouteAdapter } from "./routing";

export const widgetRoutes = ["/activity", "/history"] as const;

export type WidgetRoute = typeof widgetRoutes[number];

export function isWidgetRoute(value: string): value is WidgetRoute {
  return (widgetRoutes as readonly string[]).includes(value);
}

function Navigation() {
  return (
    <nav aria-label="Release activity navigation" className="widget-navigation">
      <Link to="/activity">Activity</Link>
      <Link to="/history">History</Link>
    </nav>
  );
}

function ActivityPage() {
  const [updatesAcknowledged, setUpdatesAcknowledged] = useState(false);

  return (
    <section aria-labelledby="activity-title">
      <span className="widget-kicker">React Router SSR Worker</span>
      <h2 id="activity-title">Release activity</h2>
      <p className="widget-copy">The widget owns this state after hydration.</p>
      <ol className="activity-list">
        <li><strong>Design tokens</strong><span>Published 12 minutes ago</span></li>
        <li><strong>Checkout shell</strong><span>Promoted to production</span></li>
        <li><strong>Search widget</strong><span>Preview is ready</span></li>
      </ol>
      <section className="nested-widget" aria-labelledby="nested-widget-title">
        <div>
          <span className="widget-kicker">Nested v-frame</span>
          <h3 id="nested-widget-title">Workspace inventory</h3>
        </div>
        <v-frame
          adopt
          className="nested-workspace-widget"
          src="/widgets/qwik/inventory"
          aria-label="Nested Qwik workspace inventory widget"
        />
      </section>
      <button type="button" onClick={() => setUpdatesAcknowledged(true)}>
        Acknowledge updates
      </button>
      <output aria-live="polite">
        {updatesAcknowledged ? "All caught up" : "3 updates waiting"}
      </output>
    </section>
  );
}

function HistoryPage() {
  return (
    <section aria-labelledby="history-title">
      <span className="widget-kicker">React Router SSR Worker</span>
      <h2 id="history-title">Release history</h2>
      <p className="widget-copy">Recent releases remain available inside this isolated router.</p>
      <ol className="history-list">
        <li><time dateTime="2026-07-13">Yesterday</time><span>Search widget preview created</span></li>
        <li><time dateTime="2026-07-10">Jul 10</time><span>Checkout shell promoted</span></li>
        <li><time dateTime="2026-07-02">Jul 2</time><span>Design tokens published</span></li>
      </ol>
    </section>
  );
}

function CurrentRoute() {
  const location = useLocation();
  return <p className="current-route">Current route: <code>{location.pathname}</code></p>;
}

export interface ReleaseActivityWidgetProps {
  routingFrameId: string;
}

export function ReleaseActivityWidget({ routingFrameId }: ReleaseActivityWidgetProps) {
  useWidgetRouteAdapter(routingFrameId);

  return (
    <main className="activity-widget">
      <Navigation />
      <CurrentRoute />
      <Routes>
        <Route path="/activity" element={<ActivityPage />} />
        <Route path="/history" element={<HistoryPage />} />
        <Route path="*" element={<Navigate replace to="/activity" />} />
      </Routes>
    </main>
  );
}

export const widgetStyle = `
  .activity-widget { height: 100%; padding: 1.4rem; border-radius: 1rem; background: #172554; color: #eff6ff; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
  .widget-navigation { display: flex; gap: 0.45rem; margin-bottom: 1.3rem; }
  .widget-navigation a { padding: 0.45rem 0.65rem; border: 1px solid #4f70a7; border-radius: 999px; color: #dbeafe; font-size: 0.8rem; font-weight: 700; text-decoration: none; }
  .widget-navigation a[aria-current="page"] { border-color: #93c5fd; background: #eff6ff; color: #172554; }
  .widget-kicker { color: #93c5fd; font-size: 0.72rem; font-weight: 800; letter-spacing: 0.09em; text-transform: uppercase; }
  .activity-widget h2 { margin: 0.45rem 0 0; font-size: 1.55rem; }
  .widget-copy, .current-route { margin: 0.35rem 0 1.2rem; color: #bfdbfe; }
  .current-route { margin: -0.8rem 0 1.2rem; font-size: 0.78rem; }
  .widget-copy code, .current-route code { color: #fff; }
  .activity-list, .history-list { display: grid; gap: 0.75rem; margin: 0; padding: 0; list-style: none; }
  .activity-list li, .history-list li { display: flex; justify-content: space-between; gap: 1rem; padding-bottom: 0.7rem; border-bottom: 1px solid #334e83; }
  .activity-list span, .history-list span, .history-list time { color: #bfdbfe; font-size: 0.82rem; text-align: right; }
  .history-list time { min-width: 4.5rem; text-align: left; }
  .nested-widget { margin-top: 1.2rem; padding: 1rem; border: 1px solid #334e83; border-radius: 0.8rem; background: #10204c; }
  .nested-widget h3 { margin: 0.25rem 0 0.8rem; }
  .nested-workspace-widget { display: block; min-height: 24rem; }
  .activity-widget button { margin-top: 1.2rem; padding: 0.65rem 0.9rem; border: 0; border-radius: 0.65rem; background: #60a5fa; color: #10204c; font: inherit; font-weight: 800; cursor: pointer; }
  .activity-widget output { display: block; margin-top: 0.65rem; color: #bfdbfe; font-size: 0.82rem; }
`;

// examples/workers-composition/workers/qwik/src/widget.tsx
/** @jsxImportSource @builder.io/qwik */
import { $, component$, useSignal } from "@builder.io/qwik";

const routingProtocol = "v-frame-routing";
const routingVersion = 1;

export type WidgetRoute = "/inventory" | "/catalog";

export function isWidgetRoute(value: string): value is WidgetRoute {
  return value === "/inventory" || value === "/catalog";
}

const requestHostNavigation = $((route: WidgetRoute) => {
  const sessionId = sessionStorage.getItem("v-frame:routing-session");
  if (sessionId === null) {
    return;
  }

  const channel = new BroadcastChannel(`v-frame:routing:v1:${sessionId}`);
  channel.postMessage({
    protocol: routingProtocol,
    version: routingVersion,
    sessionId,
    messageId: crypto.randomUUID(),
    source: "qwik",
    target: "host",
    kind: "navigate-request",
    route,
    mode: "push",
  });
  setTimeout(() => channel.close(), 0);
});

export interface WorkspaceWidgetProps {
  initialRoute: WidgetRoute;
}

export const WorkspaceWidget = component$(({ initialRoute }: WorkspaceWidgetProps) => {
  const availableItems = useSignal(3);
  const currentRoute = useSignal<WidgetRoute>(initialRoute);

  if (currentRoute.value === "/catalog") {
    return (
      <section class="inventory-widget" aria-labelledby="catalog-title">
        <span class="widget-kicker">Qwik SSR Worker</span>
        <div class="inventory-heading">
          <div>
            <h2 id="catalog-title">Workspace catalog</h2>
            <p>This route is rendered and resumed by the independent Qwik application.</p>
          </div>
          <strong>3 collections</strong>
        </div>
        <div class="inventory-grid">
          <article><strong>Field work</strong><span>Portable tools for notes and travel</span></article>
          <article><strong>Everyday carry</strong><span>Compact essentials for the commute</span></article>
          <article><strong>Studio light</strong><span>Warm lighting for focused work</span></article>
        </div>
        <div class="inventory-actions">
          <button
            type="button"
            class="inventory-link"
            onClick$={async () => {
              currentRoute.value = "/inventory";
              await requestHostNavigation("/inventory");
            }}
          >
            Back to inventory
          </button>
        </div>
      </section>
    );
  }

  return (
    <section class="inventory-widget" aria-labelledby="inventory-title">
      <span class="widget-kicker">Qwik SSR Worker</span>
      <div class="inventory-heading">
        <div>
          <h2 id="inventory-title">Workspace inventory</h2>
          <p>Resumable markup rendered independently at the edge.</p>
        </div>
        <strong>{availableItems.value} available</strong>
      </div>
      <div class="inventory-grid">
        <article><strong>Edge Notebook</strong><span>Offline-first field notes</span><b>€24</b></article>
        <article><strong>Transit Pack</strong><span>Compact everyday carry</span><b>€68</b></article>
        <article><strong>Signal Lamp</strong><span>Warm, dimmable workspace light</span><b>€42</b></article>
      </div>
      <div class="inventory-actions">
        <button
          type="button"
          onClick$={() => {
            availableItems.value += 1;
          }}
        >
          Restock one item
        </button>
        <button
          type="button"
          class="inventory-link"
          onClick$={async () => {
            currentRoute.value = "/catalog";
            await requestHostNavigation("/catalog");
          }}
        >
          View catalog
        </button>
      </div>
    </section>
  );
});

export const widgetStyle = `
  .inventory-widget { height: 100%; padding: 1.4rem; border: 1px solid #d0d5dd; border-radius: 1rem; background: #fff; color: #101828; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
  .widget-kicker { color: #175cd3; font-size: 0.72rem; font-weight: 800; letter-spacing: 0.09em; text-transform: uppercase; }
  .inventory-heading { display: flex; align-items: end; justify-content: space-between; gap: 1rem; margin: 0.45rem 0 1.2rem; }
  .inventory-heading h2 { margin: 0; font-size: 1.55rem; }
  .inventory-heading p { margin: 0.3rem 0 0; color: #667085; }
  .inventory-heading > strong { color: #475467; font-size: 0.85rem; white-space: nowrap; }
  .inventory-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0.75rem; }
  .inventory-grid article { padding: 1rem; border: 1px solid #e4e7ec; border-radius: 0.8rem; }
  .inventory-grid article > * { display: block; }
  .inventory-grid span { margin-top: 0.3rem; color: #667085; font-size: 0.82rem; }
  .inventory-grid b { margin-top: 1rem; color: #175cd3; }
  .inventory-actions { display: flex; flex-wrap: wrap; gap: 0.65rem; margin-top: 1.2rem; }
  .inventory-actions button { padding: 0.65rem 0.9rem; border: 0; border-radius: 0.65rem; background: #175cd3; color: #fff; font: inherit; font-weight: 800; cursor: pointer; }
  .inventory-actions .inventory-link { background: #eaf2ff; color: #175cd3; }
  @media (max-width: 620px) { .inventory-grid { grid-template-columns: 1fr; } }
`;
