// examples/client/microfrontends/solid-app/src/index.tsx
import { createEffect, createRoot, createSignal, onCleanup } from "solid-js";
import { render } from "solid-js/web";
import { Dialog } from "@kobalte/core/dialog";
import { Popover } from "@kobalte/core/popover";
import { Tooltip } from "@kobalte/core/tooltip";
import "./overlay-lab.css";

function OverlayLab() {
  return (
    <main class="overlay-lab" data-library="kobalte">
      <header>
        <p>Solid</p>
        <h1>Kobalte</h1>
      </header>
      <Tooltip openDelay={0} closeDelay={0}>
        <Tooltip.Trigger class="lab-button" data-testid="tooltip-trigger">Tooltip</Tooltip.Trigger>
        <Tooltip.Portal>
          <Tooltip.Content class="overlay-content tooltip-content" data-testid="tooltip-content">
            Solid tooltip
            <Tooltip.Arrow class="overlay-arrow" />
          </Tooltip.Content>
        </Tooltip.Portal>
      </Tooltip>

      <Popover>
        <Popover.Trigger class="lab-button" data-testid="popover-trigger">Popover</Popover.Trigger>
        <Popover.Portal>
          <Popover.Content class="overlay-content popover-content" data-testid="popover-content">
            <Popover.Title>Project settings</Popover.Title>
            <label>Project name<input data-testid="popover-input" value="Relay" /></label>
            <Popover.CloseButton class="close-button">Close</Popover.CloseButton>
            <Popover.Arrow class="overlay-arrow" />
          </Popover.Content>
        </Popover.Portal>
      </Popover>

      <Dialog>
        <Dialog.Trigger class="lab-button" data-testid="dialog-trigger">Modal</Dialog.Trigger>
        <Dialog.Portal>
          <Dialog.Overlay class="dialog-overlay" />
          <div class="dialog-positioner">
            <Dialog.Content class="dialog-content" data-testid="dialog-content">
              <Dialog.Title>Solid modal</Dialog.Title>
              <Dialog.Description>Kobalte manages focus and dismissal.</Dialog.Description>
              <input data-testid="dialog-first" aria-label="Modal project name" value="Relay" />
              <Dialog.CloseButton class="close-button" data-testid="dialog-close">Close</Dialog.CloseButton>
            </Dialog.Content>
          </div>
        </Dialog.Portal>
      </Dialog>
      <p class="boundary-note">The dashed edge is the microfrontend viewport.</p>
    </main>
  );
}

const pluginPage = document.getElementById("plugins-page");
const libraryPage = document.getElementById("library-page");
const overlayLab = document.getElementById("overlay-lab");
const surface = new URL(document.URL).searchParams.get("surface");
if (!pluginPage || !libraryPage || !overlayLab) {
  throw new Error("solid-app: workspace pages are missing from index.html");
}

if (surface === "overlays") {
  render(() => <OverlayLab />, overlayLab);
}
if (surface !== "overlays") {
  const visiblePage = surface === "library" ? libraryPage : pluginPage;
  visiblePage.hidden = false;
}

createRoot(() => {
  const pluginButtons = Array.from(document.querySelectorAll<HTMLButtonElement>("[data-plugin-toggle]"));
  const [enabledPlugins, setEnabledPlugins] = createSignal(
    new Set(pluginButtons.filter((button) => button.ariaPressed === "true").map((button) => button.dataset.pluginName ?? "")),
  );
  const removePluginListeners = pluginButtons.map((button) => {
    const pluginName = button.dataset.pluginName;
    if (!pluginName) throw new Error("solid-app: plugin toggle is missing its plugin name");
    const togglePlugin = () => {
      setEnabledPlugins((currentPlugins) => {
        const nextPlugins = new Set(currentPlugins);
        if (nextPlugins.has(pluginName)) nextPlugins.delete(pluginName);
        else nextPlugins.add(pluginName);
        return nextPlugins;
      });
    };
    button.addEventListener("click", togglePlugin);
    return () => button.removeEventListener("click", togglePlugin);
});

  createEffect(() => {
    for (const button of pluginButtons) {
      const pluginName = button.dataset.pluginName ?? "";
      const enabled = enabledPlugins().has(pluginName);
      button.ariaPressed = String(enabled);
      button.textContent = enabled ? "✓" : "+";
      button.setAttribute("aria-label", `${enabled ? "Disable" : "Enable"} ${pluginName}`);
    }
  });

  onCleanup(() => removePluginListeners.forEach((removeListener) => removeListener()));
  });

const pluginSearch = document.querySelector<HTMLInputElement>("[name=plugin-search]");
const pluginCategories = Array.from(document.querySelectorAll<HTMLElement>(".plugin-category"));
const filterPlugins = () => {
  const searchTerm = pluginSearch?.value.trim().toLocaleLowerCase() ?? "";
  for (const category of pluginCategories) {
    const plugins = Array.from(category.querySelectorAll<HTMLElement>(".plugin-row"));
    for (const plugin of plugins) {
      plugin.hidden = searchTerm !== "" && !plugin.textContent?.toLocaleLowerCase().includes(searchTerm);
    }
    category.hidden = plugins.every((plugin) => plugin.hidden);
  }
};
pluginSearch?.addEventListener("input", filterPlugins);

const librarySearch = document.querySelector<HTMLInputElement>("[name=library-search]");
const libraryRows = Array.from(document.querySelectorAll<HTMLTableRowElement>("#library-entries tbody tr"));
const filterLibrary = () => {
  const searchTerm = librarySearch?.value.trim().toLocaleLowerCase() ?? "";
  for (const row of libraryRows) {
    row.hidden = searchTerm !== "" && !row.textContent?.toLocaleLowerCase().includes(searchTerm);
  }
};
librarySearch?.addEventListener("input", filterLibrary);

// examples/client/microfrontends/react-app/src/main.tsx
import { StrictMode, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { Dialog, Popover, Tooltip } from "radix-ui";
import "./styles.css";

function OverlayLab() {
  const [tooltipOpen, setTooltipOpen] = useState(false);
  const tooltipTrigger = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    const trigger = tooltipTrigger.current;
    if (!trigger) return;
    const closeTooltip = () => setTooltipOpen(false);
    trigger.addEventListener("pointerleave", closeTooltip);
    return () => trigger.removeEventListener("pointerleave", closeTooltip);
  }, []);

  return (
    <main className="overlay-lab" data-library="radix-ui">
      <header>
        <p>React</p>
        <h1>Radix UI</h1>
      </header>
      <Tooltip.Provider delayDuration={0}>
        <Tooltip.Root open={tooltipOpen} onOpenChange={setTooltipOpen}>
          <Tooltip.Trigger ref={tooltipTrigger} className="lab-button" data-testid="tooltip-trigger">Tooltip</Tooltip.Trigger>
          <Tooltip.Portal>
            <Tooltip.Content className="overlay-content tooltip-content" data-testid="tooltip-content" sideOffset={8}>
              React tooltip
              <Tooltip.Arrow className="overlay-arrow" />
            </Tooltip.Content>
          </Tooltip.Portal>
        </Tooltip.Root>
      </Tooltip.Provider>

      <Popover.Root>
        <Popover.Trigger className="lab-button" data-testid="popover-trigger">Popover</Popover.Trigger>
        <Popover.Portal>
          <Popover.Content className="overlay-content popover-content" data-testid="popover-content" side="bottom" sideOffset={8}>
            <label>Project name<input data-testid="popover-input" defaultValue="Relay" /></label>
            <Popover.Close className="close-button">Close</Popover.Close>
            <Popover.Arrow className="overlay-arrow" />
          </Popover.Content>
        </Popover.Portal>
      </Popover.Root>

      <Dialog.Root>
        <Dialog.Trigger className="lab-button" data-testid="dialog-trigger">Modal</Dialog.Trigger>
        <Dialog.Portal>
          <Dialog.Overlay className="dialog-overlay" />
          <Dialog.Content className="dialog-content" data-testid="dialog-content">
            <Dialog.Title>React modal</Dialog.Title>
            <Dialog.Description>Radix manages focus and dismissal.</Dialog.Description>
            <input data-testid="dialog-first" aria-label="Modal project name" defaultValue="Relay" />
            <Dialog.Close className="close-button" data-testid="dialog-close">Close</Dialog.Close>
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>
      <p className="boundary-note">The dashed edge is the microfrontend viewport.</p>
    </main>
  );
}

const root = document.getElementById("root");
if (!root) throw new Error("react-app: missing #root mount element in index.html");

createRoot(root).render(
  <StrictMode>
    <OverlayLab />
  </StrictMode>,
);
