// examples/workers-composition/workers/react-router/src/index.tsx
import { renderToString } from "react-dom/server";
import { StaticRouter } from "react-router";

import {
  isWidgetRoute,
  ReleaseActivityWidget,
  type WidgetRoute,
  widgetStyle,
} from "./widget";

const clientModulePath = "/assets/react-router-widget-client.js";
const contentType = "text/html; charset=utf-8";

interface RenderContext {
  basename: string;
  route: WidgetRoute;
  routingFrameId: string;
  virtualPath: string;
}

function normalizedBasePath(value: string | null): string {
  if (value === null || !value.startsWith("/")) {
    return "/";
  }
  const normalized = value.replace(/\/+$/, "");
  return normalized === "" ? "/" : normalized;
}

function requestedRoute(value: string | null): WidgetRoute {
  return value !== null && isWidgetRoute(value) ? value : "/activity";
}

function requestedFrameId(value: string | null): string {
  return value === null ? "react-router-widget" : value;
}

function virtualPath(basename: string, route: WidgetRoute): string {
  return basename === "/" ? route : `${basename}${route}`;
}

function renderContext(basename: string, route: WidgetRoute, routingFrameId: string): RenderContext {
  return { basename, route, routingFrameId, virtualPath: virtualPath(basename, route) };
}

function renderWidget(context: RenderContext): string {
  return renderToString(
    <div
      id="react-router-widget-root"
      data-router-basename={context.basename}
      data-routing-frame-id={context.routingFrameId}
    >
      <StaticRouter basename={context.basename} location={context.virtualPath}>
        <ReleaseActivityWidget routingFrameId={context.routingFrameId} />
      </StaticRouter>
    </div>,
  );
}

function clientModuleURL(basename: string): string {
  return basename === "/" ? clientModulePath : `${basename}${clientModulePath}`;
}

function materializedDocument(markup: string, moduleURL: string): string {
  return `<v-html lang="en"><v-head><style>v-html, v-body { display: block; } v-head { display: none; } ${widgetStyle}</style></v-head><v-body>${markup}<script type="application/vnd.v-frame" data-v-frame-script data-v-frame-type="module" src="${moduleURL}"></script></v-body></v-html>`;
}

function networkDocument(markup: string, moduleURL: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${widgetStyle}</style></head><body>${markup}<script type="module" src="${moduleURL}"></script></body></html>`;
}

function documentResponse(context: RenderContext): Response {
  return new Response(networkDocument(renderWidget(context), clientModuleURL(context.basename)), {
    headers: { "Content-Type": contentType },
  });
}

function previewResponse(context: RenderContext): Response {
  return new Response(materializedDocument(renderWidget(context), clientModuleURL(context.basename)), {
    headers: { "Content-Type": contentType },
  });
}

export default {
  fetch(request: Request): Response {
    if (request.method !== "GET") {
      return new Response("method not allowed", { status: 405, headers: { Allow: "GET" } });
    }

    const url = new URL(request.url);
    if (isWidgetRoute(url.pathname)) {
      return documentResponse(renderContext("/", url.pathname, "react-router-widget"));
    }
    if (url.pathname === "/document" || url.pathname === "/preview") {
      const context = renderContext(
        normalizedBasePath(url.searchParams.get("base")),
        requestedRoute(url.searchParams.get("route")),
        requestedFrameId(url.searchParams.get("frameId")),
      );
      return url.pathname === "/document" ? documentResponse(context) : previewResponse(context);
    }
    return new Response("React Router widget not found", { status: 404 });
  },
} satisfies ExportedHandler;

// examples/ssr/apps/qwik/src/index.tsx
/** @jsxImportSource @builder.io/qwik */
import { renderToStream } from "@builder.io/qwik/server";
import { manifest } from "./manifest.generated.js";
import {
  isWidgetRoute,
  type RoutingFrameId,
  type WikipediaArticleKey,
  type WidgetRoute,
  widgetStyle,
  WorkspaceWidget,
} from "./widget";

type WidgetEndpoint = WidgetRoute | "/document";

function isWidgetEndpoint(pathname: string): pathname is WidgetEndpoint {
  return isWidgetRoute(pathname) || pathname === "/document";
}

function widgetBuildBase(url: URL): string {
  const requestedBase = url.searchParams.get("base");
  if (requestedBase === "/build/" || requestedBase === "/widgets/qwik/build/") {
    return requestedBase;
  }
  return "/build/";
}

function requestedRoute(url: URL, pathname: WidgetEndpoint): WidgetRoute {
  if (isWidgetRoute(pathname)) {
    return pathname;
  }
  const route = url.searchParams.get("route");
  return route !== null && isWidgetRoute(route) ? route : "/inventory";
}

function requestedFrameId(url: URL): RoutingFrameId {
  return url.searchParams.get("frameId") === "qwik" ? "qwik" : "";
}

function requestedSurface(url: URL): "definition" | "page" | "profile" {
  const surface = url.searchParams.get("surface");
  if (surface === "definition" || surface === "profile") return surface;
  return "page";
}

function requestedArticle(url: URL): WikipediaArticleKey {
  const article = url.searchParams.get("article");
  if (article === "brief" || article === "research") return article;
  return "migration";
}

async function renderWidget(url: URL, pathname: WidgetEndpoint): Promise<string> {
  const chunks: string[] = [];
  await renderToStream(
    <WorkspaceWidget
      articleKey={requestedArticle(url)}
      initialRoute={requestedRoute(url, pathname)}
      routingFrameId={requestedFrameId(url)}
      surface={requestedSurface(url)}
    />,
    {
      base: widgetBuildBase(url),
      containerTagName: "div",
      manifest,
      preloader: false,
      qwikLoader: "module",
      snapshot: true,
      stream: {
        write(chunk) {
          chunks.push(chunk);
        },
      },
      streaming: { inOrder: { strategy: "disabled" } },
    },
  );
  return chunks.join("");
}

function networkDocument(markup: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${widgetStyle}</style></head><body>${markup}</body></html>`;
}

export default {
  async fetch(request: Request): Promise<Response> {
    if (request.method !== "GET") {
      return new Response("method not allowed", {
        status: 405,
        headers: { Allow: "GET" },
      });
    }

    const url = new URL(request.url);
    const { pathname } = url;
    if (!isWidgetEndpoint(pathname)) {
      return new Response("Qwik widget not found", { status: 404 });
    }

    const markup = await renderWidget(url, pathname);
    return new Response(networkDocument(markup), {
      headers: {
        "Cache-Control": "no-store",
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  },
} satisfies ExportedHandler;
