// examples/ssr/apps/react-router/app/widget.tsx
import { Button } from "@comp0/react";
import { useEffect, useRef, useState } from "react";
import { Navigate, Route, Routes } from "react-router";

import { useWidgetRouteAdapter } from "./routing";

export const widgetRoutes = ["/activity", "/research", "/brief", "/plugins"] as const;

export type WidgetRoute = (typeof widgetRoutes)[number];

interface TranscriptStep {
  detail: string;
  title: string;
}

interface ThreadTranscript {
  articleKey: "brief" | "migration" | "research";
  articleTitle: string;
  heading: string;
  prompt: string;
  response: string;
  steps: readonly TranscriptStep[];
}

const threadTranscripts = {
  migration: {
    articleKey: "migration",
    articleTitle: "blue–green deployment",
    heading: "Migration conversation",
    prompt:
      "Help me plan the platform migration. I need a safe rollout sequence that keeps the current API available while teams move over.",
    response:
      "I’d split the migration into three reversible stages so each team can move independently.",
    steps: [
      {
        title: "Stabilize the boundary.",
        detail: "Wrap the current API in a measured compatibility layer.",
      },
      {
        title: "Mirror read traffic.",
        detail: "Compare both paths before moving any writes.",
      },
      {
        title: "Move one owner at a time.",
        detail: "Keep a short rollback window after every cutover.",
      },
    ],
  },
  research: {
    articleKey: "research",
    articleTitle: "thematic analysis",
    heading: "Customer research conversation",
    prompt:
      "Turn our customer interviews into a focused readout with themes, evidence, and a clear next decision.",
    response:
      "I’d organize the interviews around repeated needs, then separate observations from product implications.",
    steps: [
      {
        title: "Code the evidence.",
        detail: "Tag concrete statements before translating them into feature requests.",
      },
      {
        title: "Group repeated needs.",
        detail:
          "Cluster observations and note which customer segments share each pattern.",
      },
      {
        title: "Choose the next question.",
        detail: "Use the strongest unresolved theme to shape a follow-up study.",
      },
    ],
  },
  brief: {
    articleKey: "brief",
    articleTitle: "executive summary",
    heading: "Weekly brief conversation",
    prompt:
      "Draft a weekly brief for stakeholders. It should cover progress, risks, and the decisions we need next week.",
    response:
      "I’d lead with the change in status, then give each risk an owner and a dated next action.",
    steps: [
      { title: "State the movement.", detail: "Open with what changed since last week." },
      {
        title: "Name the exposure.",
        detail: "Give each risk an impact, owner, and mitigation.",
      },
      {
        title: "Request decisions.",
        detail: "End with the smallest choices that unblock the coming week.",
      },
    ],
  },
} as const satisfies Record<string, ThreadTranscript>;

export function isWidgetRoute(value: string): value is WidgetRoute {
  return (widgetRoutes as readonly string[]).includes(value);
}

function TranscriptPage({ transcript }: { transcript: ThreadTranscript }) {
  const [responseSaved, setResponseSaved] = useState(false);
  const previewTriggerRef = useRef<HTMLButtonElement>(null);
  const previewPopoverRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const previewTrigger = previewTriggerRef.current;
    const previewPopover = previewPopoverRef.current;
    if (previewTrigger === null || previewPopover === null) return;

    let closeTimer: ReturnType<typeof globalThis.setTimeout> | undefined;
    const clearScheduledClose = () => {
      if (closeTimer === undefined) return;
      clearTimeout(closeTimer);
      closeTimer = undefined;
    };
    const positionPreview = () => {
      const anchor = previewTrigger.getBoundingClientRect();
      const hostViewport = window;
      const horizontalMargin = 16;
      const anchorGap = 8;
      const previewWidth = Math.min(352, hostViewport.innerWidth - horizontalMargin * 2);
      const left = Math.min(
        Math.max(horizontalMargin, anchor.left - 8),
        hostViewport.innerWidth - previewWidth - horizontalMargin,
      );
      const previewHeight = previewPopover.offsetHeight;
      const fitsBelow =
        anchor.bottom + anchorGap + previewHeight <=
        hostViewport.innerHeight - horizontalMargin;
      const top = fitsBelow
        ? anchor.bottom + anchorGap
        : Math.max(horizontalMargin, anchor.top - anchorGap - previewHeight);
      previewPopover.style.setProperty("--preview-left", `${left}px`);
      previewPopover.style.setProperty("--preview-top", `${top}px`);
    };
    const openPreview = () => {
      clearScheduledClose();
      if (!previewPopover.matches(":popover-open")) previewPopover.showPopover();
      positionPreview();
    };
    const closePreview = () => {
      clearScheduledClose();
      if (previewPopover.matches(":popover-open")) previewPopover.hidePopover();
    };
    const schedulePreviewClose = () => {
      clearScheduledClose();
      closeTimer = globalThis.setTimeout(() => {
        closeTimer = undefined;
        if (
          previewTrigger.matches(":hover") ||
          previewTrigger === previewTrigger.ownerDocument.activeElement ||
          previewPopover.matches(":hover")
        )
          return;
        closePreview();
      }, 80);
    };
    const closePreviewOnEscape: EventListener = (event) => {
      if ((event as Event & { key?: string }).key === "Escape") closePreview();
    };

    previewTrigger.addEventListener("pointerenter", openPreview);
    previewTrigger.addEventListener("pointerleave", schedulePreviewClose);
    previewTrigger.addEventListener("focus", openPreview);
    previewTrigger.addEventListener("blur", schedulePreviewClose);
    previewTrigger.addEventListener("keydown", closePreviewOnEscape);
    previewPopover.addEventListener("pointerenter", clearScheduledClose);
    previewPopover.addEventListener("pointerleave", schedulePreviewClose);
    window.addEventListener("resize", positionPreview);
    window.addEventListener("scroll", positionPreview);

    return () => {
      clearScheduledClose();
      previewTrigger.removeEventListener("pointerenter", openPreview);
      previewTrigger.removeEventListener("pointerleave", schedulePreviewClose);
      previewTrigger.removeEventListener("focus", openPreview);
      previewTrigger.removeEventListener("blur", schedulePreviewClose);
      previewTrigger.removeEventListener("keydown", closePreviewOnEscape);
      previewPopover.removeEventListener("pointerenter", clearScheduledClose);
      previewPopover.removeEventListener("pointerleave", schedulePreviewClose);
      window.removeEventListener("resize", positionPreview);
      window.removeEventListener("scroll", positionPreview);
      closePreview();
    };
  }, []);

  return (
    <section id="transcript" aria-labelledby="transcript-title">
      <h2 id="transcript-title" className="sr-only">
        {transcript.heading}
      </h2>
      <div className="conversation-thread">
        <article className="conversation-message conversation-message-user">
          <div className="message-content">
            <p>{transcript.prompt}</p>
          </div>
        </article>
        <article className="conversation-message conversation-message-assistant">
          <div className="message-content">
            <p>{transcript.response}</p>
            <ol className="activity-list">
              {transcript.steps.map((step) => (
                <li key={step.title}>
                  <strong>{step.title}</strong>
                  <span>{step.detail}</span>
                </li>
              ))}
            </ol>
            <p className="reference-copy">
              A useful reference is{" "}
              <button
                ref={previewTriggerRef}
                type="button"
                className="wikipedia-term"
                aria-describedby="wikipedia-preview"
              >
                {transcript.articleTitle}
              </button>
              . Hover or focus the term for a preview.
            </p>
            <div
              ref={previewPopoverRef}
              id="wikipedia-preview"
              className="preview-popover"
              popover="manual"
              role="tooltip"
            >
              <div
                className="nested-widget-surface"
                data-composition-label="Qwik Wikipedia preview frontend"
              >
                <v-frame
                  adopt
                  className="nested-workspace-widget"
                  src={`/widgets/qwik/inventory?surface=definition&article=${transcript.articleKey}`}
                  aria-label={`${transcript.articleTitle} Wikipedia preview from the nested Qwik frontend`}
                />
              </div>
            </div>
            <div className="activity-actions">
              <Button type="button" onClick={() => setResponseSaved(true)}>
                ♡ Save
              </Button>
              <output aria-live="polite">{responseSaved ? "Saved" : ""}</output>
            </div>
          </div>
        </article>
      </div>
    </section>
  );
}

function PluginsPage() {
  const [enabledPlugins, setEnabledPlugins] = useState(["wikipedia", "files"]);
  const [searchQuery, setSearchQuery] = useState("");
  const togglePlugin = (plugin: string) => {
    setEnabledPlugins((currentPlugins) =>
      currentPlugins.includes(plugin)
        ? currentPlugins.filter((enabledPlugin) => enabledPlugin !== plugin)
        : [...currentPlugins, plugin],
    );
  };

  const plugins = [
    [
      "wikipedia",
      "W",
      "Wikipedia",
      "Preview relevant articles beside terms in a response.",
    ],
    ["files", "F", "File search", "Find supporting passages in workspace documents."],
    ["analysis", "D", "Data analysis", "Inspect tables and calculate quick comparisons."],
  ] as const;
  const normalizedSearchQuery = searchQuery.trim().toLocaleLowerCase();
  const visiblePlugins = plugins.filter(([, , name, description]) => {
    return (
      normalizedSearchQuery === "" ||
      `${name} ${description}`.toLocaleLowerCase().includes(normalizedSearchQuery)
    );
  });

  return (
    <section id="plugins" aria-labelledby="plugins-title">
      <header className="plugin-heading">
        <div>
          <h2 id="plugins-title">Plugins</h2>
          <p className="widget-copy">
            Work across your favorite tools from one conversation.
          </p>
        </div>
        <label className="plugin-search">
          <span className="sr-only">Search plugins</span>
          <input
            name="plugin-search"
            type="search"
            placeholder="Search plugins"
            value={searchQuery}
            onChange={(event) => {
              const searchInput = event.currentTarget as unknown as { value: string };
              setSearchQuery(searchInput.value);
            }}
          />
        </label>
      </header>
      <section className="installed-plugins" aria-labelledby="installed-plugins-title">
        <h3 id="installed-plugins-title">Installed</h3>
        <div className="installed-row">
          {plugins
            .filter(([key]) => enabledPlugins.includes(key))
            .map(([key, mark, name]) => (
              <span className="plugin-mark" title={name} key={key}>
                {mark}
              </span>
            ))}
        </div>
      </section>
      <section className="plugin-category" aria-labelledby="featured-plugins-title">
        <h3 id="featured-plugins-title">Featured</h3>
        <div className="plugin-list">
          {visiblePlugins.map(([key, mark, name, description]) => {
            const enabled = enabledPlugins.includes(key);
            return (
              <article className="plugin" key={key}>
                <span className="plugin-mark" aria-hidden="true">
                  {mark}
                </span>
                <div>
                  <strong>{name}</strong>
                  <p>{description}</p>
                </div>
                <Button
                  type="button"
                  aria-pressed={enabled}
                  onClick={() => togglePlugin(key)}
                >
                  {enabled ? "Enabled" : "Enable"}
                </Button>
              </article>
            );
          })}
        </div>
      </section>
    </section>
  );
}

export interface ReleaseActivityWidgetProps {
  routingFrameId: string;
}

export function ReleaseActivityWidget({ routingFrameId }: ReleaseActivityWidgetProps) {
  useWidgetRouteAdapter(routingFrameId);

  return (
    <main className="activity-widget">
      <Routes>
        <Route
          path="/activity"
          element={<TranscriptPage transcript={threadTranscripts.migration} />}
        />
        <Route
          path="/research"
          element={<TranscriptPage transcript={threadTranscripts.research} />}
        />
        <Route
          path="/brief"
          element={<TranscriptPage transcript={threadTranscripts.brief} />}
        />
        <Route path="/plugins" element={<PluginsPage />} />
        <Route path="*" element={<Navigate replace to="/activity" />} />
      </Routes>
    </main>
  );
}

export const widgetStyle = `
  :root { color-scheme: only dark; }
  * { box-sizing: border-box; }
  .activity-widget { min-height: 100%; padding: 1.25rem; background: #0d0d0f; color: #f4f4f5; font-family: Inter, ui-sans-serif, system-ui, sans-serif; -webkit-font-smoothing: antialiased; }
  .activity-widget h2 { margin: 0; color: #f4f4f5; font-size: 1.35rem; font-weight: 600; letter-spacing: -0.025em; }
  .widget-copy { max-width: 62ch; margin: 0.45rem 0 1.2rem; color: #a1a1aa; font-size: 0.8125rem; line-height: 1.6; }
  .conversation-thread { margin-top: 1rem; }
  .conversation-message { display: grid; grid-template-columns: 1.75rem minmax(0, 1fr); gap: 0.85rem; padding: 1rem 0; border-top: 1px solid rgba(255, 255, 255, 0.09); }
  .message-avatar { display: grid; width: 1.75rem; height: 1.75rem; place-items: center; border: 1px solid rgba(255, 255, 255, 0.12); border-radius: 0.45rem; font-size: 0.625rem; font-weight: 700; }
  .message-avatar-user { background: #18181b; }
  .message-avatar-relay { border-color: transparent; background: #10a37f; color: white; }
  .message-content > strong { color: #f4f4f5; font-size: 0.8125rem; font-weight: 600; }
  .message-content > p { margin: 0.55rem 0 0; color: #e4e4e7; font-size: 0.875rem; line-height: 1.7; }
  .activity-list { display: grid; gap: 0.8rem; margin: 1rem 0 0; padding-left: 1.25rem; }
  .activity-list li { padding-left: 0.2rem; color: #e4e4e7; font-size: 0.8125rem; line-height: 1.65; }
  .activity-list strong { color: #f4f4f5; font-weight: 600; }
  .activity-list span { margin-left: 0.3rem; color: #a1a1aa; }
  .reference-copy { margin-top: 1rem !important; }
  .wikipedia-term { padding: 0; border: 0; border-bottom: 1px dashed #34d399; background: transparent; color: #6ee7b7; cursor: help; font: inherit; }
  .wikipedia-term:focus-visible { outline: 2px solid #6ee7b7; outline-offset: 3px; }
  .preview-popover { position: fixed; inset: var(--preview-top, 1rem) auto auto var(--preview-left, 1rem); width: min(22rem, calc(100vw - 2rem)); margin: 0; padding: 0.65rem; overflow: hidden; border: 1px solid rgba(255, 255, 255, 0.14); border-radius: 0.75rem; background: #1b1b1f; color: #f4f4f5; }
  .preview-popover:not(:popover-open) { display: none; }
  .nested-widget-surface { position: relative; border-radius: 0.55rem; }
  .nested-workspace-widget { display: block; min-height: 10.5rem; border: 1px solid rgba(255, 255, 255, 0.09); border-radius: 0.55rem; overflow: hidden; }
  .activity-widget[data-composition-visible] .nested-widget-surface::before { position: absolute; z-index: 4; border: 2px solid #a78bfa; border-radius: inherit; background: color-mix(in srgb, #a78bfa 7%, transparent); content: ""; inset: 0; pointer-events: none; }
  .activity-widget[data-composition-visible] .nested-widget-surface::after { position: absolute; z-index: 5; top: 0.45rem; right: 0.45rem; padding: 0.22rem 0.42rem; border-radius: 999px; background: #a78bfa; color: white; content: attr(data-composition-label); font-size: 0.625rem; font-weight: 600; pointer-events: none; }
  .activity-actions { display: flex; align-items: center; gap: 0.7rem; margin-top: 1rem; }
  .activity-actions button, .plugin button { min-height: 2.125rem; padding: 0.4rem 0.7rem; border: 0; border-radius: 0.5rem; background: #10a37f; color: white; cursor: pointer; font: inherit; font-size: 0.75rem; font-weight: 600; }
  .activity-actions output { color: #71717a; font-size: 0.75rem; }
  .activity-actions button:focus-visible, .plugin button:focus-visible { outline: 2px solid #6ee7b7; outline-offset: 2px; }
  .plugin-list { display: grid; border-top: 1px solid rgba(255, 255, 255, 0.09); }
  .plugin { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 0.9rem; padding: 1rem 0; border-bottom: 1px solid rgba(255, 255, 255, 0.07); }
  .plugin-mark { display: grid; width: 2rem; height: 2rem; place-items: center; border: 1px solid rgba(255, 255, 255, 0.12); border-radius: 0.55rem; background: #18181b; color: #d4d4d8; font-size: 0.75rem; font-weight: 650; }
  .plugin > div { min-width: 0; }
  .plugin strong { color: #e4e4e7; font-size: 0.8125rem; font-weight: 600; }
  .plugin p { margin: 0.25rem 0 0; color: #a1a1aa; font-size: 0.8125rem; line-height: 1.5; }
  .plugin button { min-width: 5.25rem; border: 1px solid rgba(255, 255, 255, 0.12); background: #18181b; color: #e4e4e7; }
  .plugin button[aria-pressed="true"] { border-color: rgba(110, 231, 183, 0.35); color: #6ee7b7; }
  @media (max-width: 36rem) {
    .activity-widget { padding: 1.1rem; }
    .activity-actions output { font-size: 0.875rem; }
    .widget-copy, .message-content > p, .activity-list li, .plugin strong, .plugin p { font-size: 1rem; }
    .activity-actions { align-items: flex-start; flex-direction: column; }
    .activity-actions button { min-height: 3rem; font-size: 1rem; }
    .plugin { grid-template-columns: auto minmax(0, 1fr); }
    .plugin button { grid-column: 2; min-height: 3rem; font-size: 1rem; justify-self: start; }
  }
  .sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; margin: -1px; padding: 0; border: 0; clip: rect(0, 0, 0, 0); white-space: nowrap; }
  .activity-widget { min-height: 100%; padding: 1rem 0; background: #000; color: #f5f5f5; }
  .activity-widget > section { width: min(100%, 48rem); margin: 0 auto; }
  .conversation-message { display: block; min-width: 0; padding: 1.15rem 0; border: 0; }
  .conversation-message-user { display: flex; justify-content: flex-end; }
  .conversation-message-user .message-content { max-width: min(36rem, 82%); padding: 0.65rem 1rem; border-radius: 1.25rem; background: #2f2f2f; }
  .message-content > p { margin: 0; color: #ececec; font-size: 0.9375rem; line-height: 1.72; }
  .activity-list li { color: #ececec; font-size: 0.9375rem; }
  .activity-list span { color: #b4b4b4; }
  .wikipedia-term { border-bottom-color: #b4b4b4; color: #f5f5f5; }
  .preview-popover { width: min(22.5rem, calc(100vw - 1.5rem)); height: 12.5rem; padding: 0; border-color: #444; border-radius: 0.85rem; background: #212121; color: #f5f5f5; }
  .nested-widget-surface, .nested-workspace-widget { width: 100%; height: 100%; min-height: 0; border: 0; border-radius: inherit; }
  .activity-actions { gap: 0.35rem; margin-top: 0.8rem; }
  .activity-actions button { min-height: 1.9rem; padding: 0.3rem 0.5rem; background: transparent; color: #a0a0a0; font-weight: 400; }
  .activity-actions button:hover { background: #212121; color: white; }
  #transcript { padding: 1.5rem 1.5rem 3rem; }
  .conversation-thread { margin-top: 0; }
  #plugins { padding: 3rem 1.5rem 4rem; }
  .activity-widget h2 { color: #f5f5f5; font-size: 1.75rem; font-weight: 500; }
  .widget-copy { margin: 0.35rem 0 0; color: #b4b4b4; font-size: 0.875rem; }
  .plugin-heading { display: flex; min-width: 0; align-items: flex-end; justify-content: space-between; gap: 1.5rem; }
  .plugin-search { position: relative; display: block; flex: none; }
  .plugin-search::before { position: absolute; top: 50%; left: 0.75rem; color: #8e8e8e; content: "⌕"; font-size: 1rem; transform: translateY(-50%); pointer-events: none; }
  .plugin-search input { width: 15rem; height: 2.35rem; padding: 0.4rem 0.75rem 0.4rem 2rem; border: 1px solid #3f3f3f; border-radius: 999px; background: #212121; color: #f5f5f5; font: inherit; font-size: 0.8125rem; }
  .plugin-search input::placeholder { color: #a0a0a0; }
  .plugin-search input:focus-visible { outline: 2px solid white; outline-offset: 0; }
  .installed-plugins { margin-top: 2.4rem; }
  .installed-plugins h3, .plugin-category > h3 { margin: 0 0 0.65rem; color: #ececec; font-size: 0.8125rem; font-weight: 500; }
  .installed-row { display: flex; flex-wrap: wrap; gap: 0.55rem; }
  .plugin-category { margin-top: 2rem; }
  .plugin-list { grid-template-columns: repeat(2, minmax(0, 1fr)); column-gap: 2rem; border: 0; }
  .plugin { min-width: 0; gap: 0.75rem; padding: 0.8rem 0; border: 0; }
  .plugin-mark { width: 2.35rem; height: 2.35rem; border: 0; border-radius: 0.65rem; background: #242424; color: #ececec; font-size: 0.6875rem; }
  .plugin strong { color: #ececec; font-weight: 500; }
  .plugin p { overflow: hidden; color: #8e8e8e; font-size: 0.72rem; text-overflow: ellipsis; white-space: nowrap; }
  .plugin button { width: 2rem; min-width: 2rem; height: 2rem; min-height: 2rem; padding: 0; border: 0; background: transparent; color: #b4b4b4; overflow: hidden; font-size: 0; }
  .plugin button::after { content: "+"; font-size: 1.15rem; }
  .plugin button[aria-pressed="true"] { border: 0; color: #8e8e8e; }
  .plugin button[aria-pressed="true"]::after { content: "✓"; font-size: 0.8125rem; }
  @media (max-width: 36rem) {
    .activity-widget { padding: 0; }
    #transcript { padding: 0.5rem 1rem 2rem; }
    #plugins { padding: 1.5rem 1rem 3rem; }
    .conversation-message-user .message-content { max-width: 92%; }
    .plugin-heading { align-items: stretch; flex-direction: column; }
    .plugin-search, .plugin-search input { width: 100%; }
    .plugin-search input { min-height: 3rem; font-size: 1rem; }
    .plugin-list { grid-template-columns: 1fr; }
  }
`;

// examples/ssr/apps/qwik/src/widget.tsx
/** @jsxImportSource @builder.io/qwik */
import { component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";

import {
  isRoutingMessage,
  openRoutingChannel,
  postRoutingMessage,
  routingProtocol,
  routingSessionId,
  routingVersion,
} from "../../../shared/routing";

export type WidgetRoute = "/inventory" | "/catalog";
export type RoutingFrameId = "" | "qwik";
export type WikipediaArticleKey = "brief" | "migration" | "research";

const wikipediaArticles = {
  migration: {
    title: "Blue–green deployment",
    extract: "A release strategy that runs two production environments so traffic can move to a new version with a quick rollback path.",
    href: "https://en.wikipedia.org/wiki/Blue%E2%80%93green_deployment",
  },
  research: {
    title: "Thematic analysis",
    extract: "A qualitative method for identifying, analyzing, and reporting recurring patterns within a collection of material.",
    href: "https://en.wikipedia.org/wiki/Thematic_analysis",
  },
  brief: {
    title: "Executive summary",
    extract: "A short document or section that presents the purpose, major findings, and recommendations of a longer report.",
    href: "https://en.wikipedia.org/wiki/Executive_summary",
  },
} as const;

export function isWidgetRoute(value: string): value is WidgetRoute {
  return value === "/inventory" || value === "/catalog";
}

export interface WorkspaceWidgetProps {
  articleKey: WikipediaArticleKey;
  initialRoute: WidgetRoute;
  routingFrameId: RoutingFrameId;
  surface: "definition" | "page" | "profile";
}

export const WorkspaceWidget = component$(({
  articleKey,
  initialRoute,
  routingFrameId,
  surface,
}: WorkspaceWidgetProps) => {
  const currentRoute = useSignal<WidgetRoute>(initialRoute);
  const draftMessage = useSignal("");
  const messageStatus = useSignal("Relay can make mistakes. Check important details.");
  const pendingRouteReady = useSignal<WidgetRoute>();
  const routeSurface = useSignal<HTMLElement>();

  useVisibleTask$(({ cleanup }) => {
    if (routingFrameId === "") return;
    const sessionId = routingSessionId();
    if (sessionId === null) return;
    const channel = openRoutingChannel(sessionId);
    if (channel === null) return;

    const receiveRouteChange = (event: MessageEvent<unknown>) => {
      if (event.origin !== location.origin || !isRoutingMessage(event.data)) return;
      const message = event.data;
      if (
        message.sessionId !== sessionId
        || message.source !== "host"
        || message.target !== routingFrameId
        || message.kind !== "route-change"
        || message.route === undefined
        || !isWidgetRoute(message.route)
      ) return;
      if (currentRoute.value === message.route) {
        postRoutingMessage(channel, {
          protocol: routingProtocol,
          version: routingVersion,
          sessionId,
          source: routingFrameId,
          target: "host",
          kind: "route-ready",
          route: message.route,
        });
        return;
      }

      routeSurface.value = undefined;
      currentRoute.value = message.route;
      pendingRouteReady.value = message.route;
    };

    channel.addEventListener("message", receiveRouteChange);
    const didPostHello = postRoutingMessage(channel, {
      protocol: routingProtocol,
      version: routingVersion,
      sessionId,
      source: routingFrameId,
      target: "host",
      kind: "hello",
    });
    if (!didPostHello) {
      channel.removeEventListener("message", receiveRouteChange);
      channel.close();
      return;
    }

    cleanup(() => {
      channel.removeEventListener("message", receiveRouteChange);
      channel.close();
    });
  }, { strategy: "document-ready" });

  useVisibleTask$(({ track }) => {
    const requestedRoute = track(() => pendingRouteReady.value);
    const renderedSurface = track(() => routeSurface.value);
    if (requestedRoute === undefined || renderedSurface === undefined) return;

    const sessionId = routingSessionId();
    if (sessionId === null) return;
    const channel = openRoutingChannel(sessionId);
    if (channel === null) return;
    const didPostRouteReady = postRoutingMessage(channel, {
      protocol: routingProtocol,
      version: routingVersion,
      sessionId,
      source: routingFrameId,
      target: "host",
      kind: "route-ready",
      route: requestedRoute,
    });
    channel.close();
    if (didPostRouteReady) pendingRouteReady.value = undefined;
  }, { strategy: "document-ready" });

  if (surface === "definition") {
    const article = wikipediaArticles[articleKey];
    return (
      <article class="wikipedia-preview">
        <span class="widget-kicker">Wikipedia</span>
        <h2>{article.title}</h2>
        <p>{article.extract}</p>
        <a href={article.href} target="_blank" rel="noreferrer">Read the article</a>
      </article>
    );
  }

  if (surface === "profile") {
    return (
      <section class="profile-widget" aria-label="Account">
        <button type="button" class="profile-trigger" popovertarget="profile-menu">
          <span class="profile-avatar" aria-hidden="true">AM</span>
          <span class="profile-copy"><strong>Avery Morgan</strong><small>Team workspace</small></span>
          <span class="profile-more" aria-hidden="true">···</span>
        </button>
        <div id="profile-menu" class="profile-menu" popover="auto">
          <p>Avery Morgan</p>
          <button type="button">Settings</button>
          <button type="button">Keyboard shortcuts</button>
          <button type="button">Sign out</button>
        </div>
      </section>
    );
  }

  if (currentRoute.value === "/catalog") {
    return (
      <main ref={routeSurface} class="usage-widget" aria-labelledby="usage-title">
        <header class="usage-heading">
          <div>
            <h2 id="usage-title">Usage</h2>
            <p class="usage-copy">Workspace activity for the current billing period.</p>
          </div>
          <button type="button">July 2026⌄</button>
        </header>
        <section id="usage-summary" class="usage-overview" aria-label="Usage summary">
          <article><span>Messages</span><strong>1,284</strong><small>32% of plan</small></article>
          <article><span>Context</span><strong>3.8M</strong><small>tokens processed</small></article>
          <article><span>Plugin calls</span><strong>216</strong><small>this month</small></article>
        </section>
        <section class="usage-breakdown" aria-labelledby="usage-breakdown-title">
          <div class="section-heading"><h3 id="usage-breakdown-title">Usage by frontend</h3><span>Messages</span></div>
          <table>
            <tbody>
              <tr><td><span class="frontend-mark react-mark" />React conversations</td><td>937</td><td>73%</td></tr>
              <tr><td><span class="frontend-mark qwik-mark" />Qwik composer and widgets</td><td>347</td><td>27%</td></tr>
            </tbody>
          </table>
        </section>
      </main>
    );
  }

  return (
    <form
      ref={routeSurface}
      class="composer-widget"
      onSubmit$={(event: SubmitEvent) => {
        event.preventDefault();
        if (draftMessage.value.trim() === "") return;
        draftMessage.value = "";
        messageStatus.value = "Message sent.";
      }}
    >
      <div class="composer-row">
        <button type="button" class="attach-button" aria-label="Attach files">+</button>
        <textarea
          name="message"
          aria-label="Message Relay"
          placeholder="Ask anything"
          value={draftMessage.value}
          onInput$={(event: InputEvent) => {
            const messageInput = event.target as { value: string } | null;
            if (messageInput === null) return;
            draftMessage.value = messageInput.value;
            messageStatus.value = "Relay can make mistakes. Check important details.";
          }}
        />
        <button type="submit" class="send-button" aria-label="Send message">↑</button>
      </div>
      <p aria-live="polite">{messageStatus.value}</p>
    </form>
  );
});

export const widgetStyle = `
  :root { color-scheme: only dark; }
  * { box-sizing: border-box; }
  html, body, body > div { height: 100%; margin: 0; }
  button, textarea { font: inherit; }
  button:focus-visible, textarea:focus-visible, a:focus-visible { outline: 2px solid #6ee7b7; outline-offset: 2px; }
  .widget-kicker { color: #6ee7b7; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.6875rem; font-weight: 600; letter-spacing: 0.04em; }
  .composer-widget { display: grid; min-height: 8rem; padding: 0.85rem; background: #151518; color: #f4f4f5; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
  .composer-widget textarea { width: 100%; min-height: 3rem; resize: none; border: 0; outline: 0; background: transparent; color: #f4f4f5; font-size: 0.875rem; line-height: 1.5; }
  .composer-widget textarea::placeholder { color: #71717a; }
  .usage-widget { min-height: 100%; padding: 1.25rem; background: #0d0d0f; color: #f4f4f5; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
  .usage-widget h2 { margin: 0.4rem 0 0; font-size: 1.35rem; font-weight: 600; letter-spacing: -0.025em; }
  .usage-copy { margin: 0.45rem 0 0; color: #a1a1aa; font-size: 0.8125rem; line-height: 1.55; }
  .usage-overview { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0.75rem; margin-top: 1.5rem; }
  .usage-overview article { min-width: 0; padding: 1rem; border: 1px solid rgba(255, 255, 255, 0.09); border-radius: 0.7rem; background: #151518; }
  .usage-overview article > span { display: block; color: #a1a1aa; font-size: 0.75rem; }
  .usage-overview strong { display: block; margin-top: 0.7rem; font-size: 1.4rem; font-weight: 600; font-variant-numeric: tabular-nums; }
  .usage-overview small { color: #71717a; font-size: 0.6875rem; }
  .wikipedia-preview { min-height: 100%; padding: 0.9rem; background: #151518; color: #f4f4f5; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
  .wikipedia-preview h2 { margin: 0.4rem 0 0; font-family: Georgia, "Times New Roman", serif; font-size: 1.15rem; font-weight: 600; }
  .wikipedia-preview p { margin: 0.55rem 0 0; color: #d4d4d8; font-size: 0.8125rem; line-height: 1.55; }
  .wikipedia-preview a { display: inline-block; margin-top: 0.75rem; color: #6ee7b7; font-size: 0.75rem; text-decoration: none; }
  .wikipedia-preview a:hover { text-decoration: underline; }
  .profile-widget { min-height: 100%; background: #101012; color: #f4f4f5; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
  .profile-trigger { display: grid; width: 100%; min-height: 3rem; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 0.6rem; padding: 0.45rem; border: 0; border-radius: 0.5rem; background: transparent; color: inherit; cursor: pointer; text-align: left; }
  .profile-trigger:hover { background: rgba(255, 255, 255, 0.05); }
  .profile-avatar { display: grid; width: 1.9rem; height: 1.9rem; place-items: center; border-radius: 999px; background: #3f3f46; color: white; font-size: 0.625rem; font-weight: 600; }
  .profile-copy { display: grid; min-width: 0; gap: 0.12rem; }
  .profile-copy strong { overflow: hidden; color: #e4e4e7; font-size: 0.75rem; font-weight: 600; text-overflow: ellipsis; white-space: nowrap; }
  .profile-copy small, .profile-more { color: #71717a; font-size: 0.6875rem; }
  .profile-menu { inset: 0 auto auto 0.8rem; width: 14.4rem; margin: 0; padding: 0.45rem; transform: translateY(calc(-100% - 0.6rem)); border: 1px solid rgba(255, 255, 255, 0.14); border-radius: 0.7rem; background: #1b1b1f; color: #f4f4f5; }
  .profile-menu p { margin: 0; padding: 0.55rem 0.6rem; border-bottom: 1px solid rgba(255, 255, 255, 0.09); color: #a1a1aa; font-size: 0.75rem; }
  .profile-menu button { display: block; width: 100%; min-height: 2.25rem; padding: 0.45rem 0.6rem; border: 0; border-radius: 0.45rem; background: transparent; color: #e4e4e7; cursor: pointer; font-size: 0.75rem; text-align: left; }
  .profile-menu button:hover { background: rgba(255, 255, 255, 0.05); }
  @media (max-width: 36rem) {
    .composer-widget textarea, .usage-copy, .usage-overview article > span, .wikipedia-preview p { font-size: 1rem; }
    .usage-overview { grid-template-columns: 1fr; }
    .wikipedia-preview a { font-size: 0.875rem; }
  }
  .composer-widget { display: block; height: 100%; min-height: 0; padding: 0.55rem 0.65rem 0.35rem; background: #212121; color: #f5f5f5; }
  .composer-row { display: flex; min-width: 0; height: 3.55rem; align-items: center; gap: 0.45rem; }
  .composer-widget textarea { min-width: 0; height: 2.75rem; min-height: 0; flex: 1; padding: 0.7rem 0.2rem; color: #f5f5f5; font-size: 0.9375rem; line-height: 1.35; }
  .composer-widget textarea::placeholder { color: #a0a0a0; }
  .composer-widget button { display: grid; width: 2rem; height: 2rem; flex: none; min-height: 2rem; padding: 0; place-items: center; border: 0; border-radius: 999px; cursor: pointer; }
  .attach-button { background: transparent; color: #d4d4d4; font-size: 1.35rem; }
  .attach-button:hover { background: #303030; }
  .send-button { background: #f5f5f5; color: #111; font-size: 1.05rem; }
  .composer-widget > p { overflow: hidden; margin: 0; color: #737373; font-size: 0.625rem; text-align: center; text-overflow: ellipsis; white-space: nowrap; }
  .usage-widget { width: min(100%, 48rem); min-height: 100%; margin: 0 auto; padding: 3rem 1.5rem 4rem; background: #000; color: #f5f5f5; }
  .usage-widget h2 { margin: 0; font-size: 1.75rem; font-weight: 500; letter-spacing: -0.035em; }
  .usage-heading { display: flex; align-items: center; justify-content: space-between; gap: 1.5rem; }
  .usage-heading button { min-height: 2.35rem; padding: 0.4rem 0.8rem; border: 1px solid #3a3a3a; border-radius: 999px; background: #212121; color: #b4b4b4; cursor: pointer; font-size: 0.8125rem; }
  .usage-copy { margin: 0.4rem 0 0; color: #a0a0a0; font-size: 0.875rem; }
  .usage-overview { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0; margin-top: 3rem; border-block: 1px solid #252525; }
  .usage-overview article { min-width: 0; padding: 1.25rem 1.5rem; border: 0; border-left: 1px solid #252525; border-radius: 0; background: transparent; }
  .usage-overview article:first-child { padding-left: 0; border-left: 0; }
  .usage-overview article > span { color: #a0a0a0; }
  .usage-overview strong { color: #f5f5f5; font-size: 1.65rem; font-weight: 500; }
  .usage-overview small { color: #737373; }
  .usage-breakdown { margin-top: 2.5rem; }
  .section-heading { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding-bottom: 0.65rem; border-bottom: 1px solid #252525; }
  .section-heading h3 { margin: 0; color: #ececec; font-size: 0.875rem; font-weight: 500; }
  .section-heading span { color: #737373; font-size: 0.75rem; }
  table { width: 100%; border-collapse: collapse; }
  td { height: 3.75rem; border-bottom: 1px solid #1d1d1d; color: #a0a0a0; font-size: 0.8125rem; font-variant-numeric: tabular-nums; }
  td:first-child { display: flex; align-items: center; gap: 0.7rem; color: #ececec; }
  td:not(:first-child) { width: 5rem; text-align: right; }
  .frontend-mark { width: 0.6rem; height: 0.6rem; flex: none; border-radius: 0.15rem; }
  .react-mark { background: #3b82f6; }
  .qwik-mark { background: #8b5cf6; }
  .wikipedia-preview { width: min(100%, 24rem); padding: 1rem; background: #212121; color: #f5f5f5; }
  .wikipedia-preview .widget-kicker { color: #a0a0a0; font-family: inherit; text-transform: uppercase; }
  .wikipedia-preview p { color: #d4d4d4; }
  .wikipedia-preview a { color: #ececec; text-decoration: underline; text-underline-offset: 0.18rem; }
  .profile-widget { background: #0d0d0d; color: #f5f5f5; }
  .profile-trigger { display: flex; height: 3.4rem; min-height: 0; gap: 0.65rem; padding: 0.45rem 0.55rem; }
  .profile-avatar { width: 2rem; height: 2rem; flex: none; background: #7c3aed; font-size: 0.6875rem; }
  .profile-copy { gap: 0.08rem; }
  .profile-copy strong { color: #ececec; font-weight: 500; }
  .profile-copy small, .profile-more { color: #737373; }
  .profile-trigger:hover { background: #212121; }
  .profile-more { margin-left: auto; }
  .profile-menu { inset: 0 auto auto 0.75rem; width: 14rem; transform: translateY(calc(-100% - 0.85rem)); border-color: #3a3a3a; border-radius: 0.65rem; background: #212121; color: #f5f5f5; }
  .profile-menu p { border-bottom-color: #333; color: #a0a0a0; }
  .profile-menu button { min-height: 2rem; color: #ececec; }
  .profile-menu button:hover { background: #303030; }
  @media (max-width: 36rem) {
    .usage-widget { padding: 1.5rem 1rem; }
    .usage-heading { align-items: flex-start; flex-direction: column; }
    .usage-heading button { min-height: 3rem; font-size: 1rem; }
    .usage-overview { grid-template-columns: 1fr; }
    .usage-overview article, .usage-overview article:first-child { padding: 1rem 0; border-left: 0; border-top: 1px solid #252525; }
    .usage-overview article:first-child { border-top: 0; }
  }
`;
